# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "project: et cetera."
email: m@cyhsu.me
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.cyhsu.me" # the base hostname & protocol for your site
twitter_username: cyhsutw
github_username:  cyhsutw
permalink: pretty
comments: true
analytics:
  provider: google
  google:
    tracking_id: 'UA-78054212-1'

kramdown:
  input: GFM
  syntax_highlighter: rouge
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]

gems:
  - jekyll-feed
